# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gateway_pb2 as gateway__pb2


class GatewayStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Invoke = channel.unary_unary(
        '/pb.Gateway/Invoke',
        request_serializer=gateway__pb2.InvokeServiceRequest.SerializeToString,
        response_deserializer=gateway__pb2.Message.FromString,
        )
    self.List = channel.unary_unary(
        '/pb.Gateway/List',
        request_serializer=gateway__pb2.Empty.SerializeToString,
        response_deserializer=gateway__pb2.Functions.FromString,
        )
    self.Deploy = channel.unary_unary(
        '/pb.Gateway/Deploy',
        request_serializer=gateway__pb2.CreateFunctionRequest.SerializeToString,
        response_deserializer=gateway__pb2.Message.FromString,
        )
    self.Delete = channel.unary_unary(
        '/pb.Gateway/Delete',
        request_serializer=gateway__pb2.DeleteFunctionRequest.SerializeToString,
        response_deserializer=gateway__pb2.Message.FromString,
        )
    self.Update = channel.unary_unary(
        '/pb.Gateway/Update',
        request_serializer=gateway__pb2.CreateFunctionRequest.SerializeToString,
        response_deserializer=gateway__pb2.Message.FromString,
        )
    self.GetMeta = channel.unary_unary(
        '/pb.Gateway/GetMeta',
        request_serializer=gateway__pb2.FunctionRequest.SerializeToString,
        response_deserializer=gateway__pb2.Function.FromString,
        )
    self.GetLog = channel.unary_unary(
        '/pb.Gateway/GetLog',
        request_serializer=gateway__pb2.FunctionRequest.SerializeToString,
        response_deserializer=gateway__pb2.Message.FromString,
        )
    self.ReplicaUpdate = channel.unary_unary(
        '/pb.Gateway/ReplicaUpdate',
        request_serializer=gateway__pb2.ScaleServiceRequest.SerializeToString,
        response_deserializer=gateway__pb2.Message.FromString,
        )
    self.Info = channel.unary_unary(
        '/pb.Gateway/Info',
        request_serializer=gateway__pb2.Empty.SerializeToString,
        response_deserializer=gateway__pb2.Message.FromString,
        )
    self.HealthCheck = channel.unary_unary(
        '/pb.Gateway/HealthCheck',
        request_serializer=gateway__pb2.Empty.SerializeToString,
        response_deserializer=gateway__pb2.Message.FromString,
        )
    self.Invokes = channel.stream_stream(
        '/pb.Gateway/Invokes',
        request_serializer=gateway__pb2.InvokeServiceRequest.SerializeToString,
        response_deserializer=gateway__pb2.Messages.FromString,
        )


class GatewayServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Invoke(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def List(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Deploy(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMeta(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReplicaUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Info(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HealthCheck(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Invokes(self, request_iterator, context):
    """stream
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GatewayServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Invoke': grpc.unary_unary_rpc_method_handler(
          servicer.Invoke,
          request_deserializer=gateway__pb2.InvokeServiceRequest.FromString,
          response_serializer=gateway__pb2.Message.SerializeToString,
      ),
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=gateway__pb2.Empty.FromString,
          response_serializer=gateway__pb2.Functions.SerializeToString,
      ),
      'Deploy': grpc.unary_unary_rpc_method_handler(
          servicer.Deploy,
          request_deserializer=gateway__pb2.CreateFunctionRequest.FromString,
          response_serializer=gateway__pb2.Message.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=gateway__pb2.DeleteFunctionRequest.FromString,
          response_serializer=gateway__pb2.Message.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=gateway__pb2.CreateFunctionRequest.FromString,
          response_serializer=gateway__pb2.Message.SerializeToString,
      ),
      'GetMeta': grpc.unary_unary_rpc_method_handler(
          servicer.GetMeta,
          request_deserializer=gateway__pb2.FunctionRequest.FromString,
          response_serializer=gateway__pb2.Function.SerializeToString,
      ),
      'GetLog': grpc.unary_unary_rpc_method_handler(
          servicer.GetLog,
          request_deserializer=gateway__pb2.FunctionRequest.FromString,
          response_serializer=gateway__pb2.Message.SerializeToString,
      ),
      'ReplicaUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.ReplicaUpdate,
          request_deserializer=gateway__pb2.ScaleServiceRequest.FromString,
          response_serializer=gateway__pb2.Message.SerializeToString,
      ),
      'Info': grpc.unary_unary_rpc_method_handler(
          servicer.Info,
          request_deserializer=gateway__pb2.Empty.FromString,
          response_serializer=gateway__pb2.Message.SerializeToString,
      ),
      'HealthCheck': grpc.unary_unary_rpc_method_handler(
          servicer.HealthCheck,
          request_deserializer=gateway__pb2.Empty.FromString,
          response_serializer=gateway__pb2.Message.SerializeToString,
      ),
      'Invokes': grpc.stream_stream_rpc_method_handler(
          servicer.Invokes,
          request_deserializer=gateway__pb2.InvokeServiceRequest.FromString,
          response_serializer=gateway__pb2.Messages.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pb.Gateway', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
